version: '3.8'
services:
  mynodejsapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: khan9205/exercisenodejs:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      PORT: "3000"
    restart: unless-stopped
